update

diff --git a/fun/3x-ui/Dockerfile b/fun/3x-ui/Dockerfile
--- a/fun/3x-ui/Dockerfile
+++ b/fun/3x-ui/Dockerfile
@@ -1,54 +1,49 @@
-# ========================================================
-# Stage: Builder
-# ========================================================
-FROM golang:1.24-alpine AS builder
-WORKDIR /app
+# Description: Dockerfile to build a lightweight 3x-ui image on Alpine Linux.
+#
+# Copyright (c) 2025 honeok <honeok@duck.com>
+#
+# Licensed under the GNU General Public License, version 2 only.
+# This program is distributed WITHOUT ANY WARRANTY.
+# See <https://www.gnu.org/licenses/old-licenses/gpl-2.0.html>.
+
+FROM --platform=$BUILDPLATFORM alpine:latest AS builder
+
+COPY build.sh .
+
+RUN set -ex \
+        && chmod +x build.sh && ./build.sh
+
+FROM --platform=$BUILDPLATFORM alpine:latest
+
+# https://docs.docker.com/build/building/multi-platform/
 ARG TARGETARCH
 
-RUN apk --no-cache --update add \
-  build-base \
-  gcc \
-  wget \
-  unzip
+WORKDIR /3x-ui
 
-COPY . .
+COPY --from=builder /tmp/x-ui/x-ui /3x-ui/3x-ui
+COPY --from=builder /tmp/xray/xray /3x-ui/bin/xray-linux-${TARGETARCH}
+COPY docker-entrypoint.sh /docker-entrypoint.sh
+COPY x-ui.sh /usr/local/bin/x-ui
 
-ENV CGO_ENABLED=1
-ENV CGO_CFLAGS="-D_LARGEFILE64_SOURCE"
-RUN go build -ldflags "-w -s" -o build/x-ui main.go
-RUN ./DockerInit.sh "$TARGETARCH"
+RUN set -ex \
+        && apk update && apk upgrade \
+        && apk add --no-cache \
+            ca-certificates \
+            tzdata \
+            fail2ban \
+        && chmod +x /docker-entrypoint.sh /usr/local/bin/x-ui \
+        && rm -f /etc/fail2ban/jail.d/alpine-ssh.conf \
+        && cp -f /etc/fail2ban/jail.conf /etc/fail2ban/jail.local \
+        && sed -i "s/^\[ssh\]$/&\nenabled = false/" /etc/fail2ban/jail.local \
+        && sed -i "s/^\[sshd\]$/&\nenabled = false/" /etc/fail2ban/jail.local \
+        && sed -i "s/#allowipv6 = auto/allowipv6 = auto/g" /etc/fail2ban/fail2ban.conf \
+        && ln -sf /3x-ui/3x-ui /usr/local/bin/3x-ui \
+        && curl -fsSL -o /3x-ui/bin/geosite.dat "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat" \
+        && curl -fsSL -o /3x-ui/bin/geoip.dat "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat" \
+        && rm -rf /var/cache/apk/* /tmp/*
 
-# ========================================================
-# Stage: Final Image of 3x-ui
-# ========================================================
-FROM alpine
-ENV TZ=Asia/Tehran
-WORKDIR /app
-
-RUN apk add --no-cache --update \
-  ca-certificates \
-  tzdata \
-  fail2ban \
-  bash
-
-COPY --from=builder /app/build/ /app/
-COPY --from=builder /app/DockerEntrypoint.sh /app/
-COPY --from=builder /app/x-ui.sh /usr/bin/x-ui
-
-
-# Configure fail2ban
-RUN rm -f /etc/fail2ban/jail.d/alpine-ssh.conf \
-  && cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local \
-  && sed -i "s/^\[ssh\]$/&\nenabled = false/" /etc/fail2ban/jail.local \
-  && sed -i "s/^\[sshd\]$/&\nenabled = false/" /etc/fail2ban/jail.local \
-  && sed -i "s/#allowipv6 = auto/allowipv6 = auto/g" /etc/fail2ban/fail2ban.conf
-
-RUN chmod +x \
-  /app/DockerEntrypoint.sh \
-  /app/x-ui \
-  /usr/bin/x-ui
-
-ENV X_UI_ENABLE_FAIL2BAN="true"
 VOLUME [ "/etc/x-ui" ]
-CMD [ "./x-ui" ]
-ENTRYPOINT [ "/app/DockerEntrypoint.sh" ]
+
+ENV TZ=Asia/Shanghai
+
+ENTRYPOINT [ "/docker-entrypoint.sh" ]
