update

diff --git a/.github/workflows/build_nginx.yml b/.github/workflows/build_nginx.yml
--- a/.github/workflows/build_nginx.yml
+++ b/.github/workflows/build_nginx.yml
@@ -21,21 +21,26 @@ jobs:
 
       - name: 'Fetch Versions and Determine Build'
         run: |
-          NGX_CVER=$(curl -fsSL "https://hub.docker.com/v2/repositories/honeok/nginx/tags" | jq -r '.results // [] | .[].name' 2>/dev/null | grep -v '^alpine$' | sort -Vr | head -n1 | cut -d'-' -f1 || echo "")
-          NGX_LVER=$(curl -fsSL "https://api.github.com/repos/nginx/nginx/releases/latest" | jq -r '.tag_name | sub("release-"; "")')
-          ZSTD_LVER=$(curl -fsSL "https://api.github.com/repos/facebook/zstd/releases/latest" | jq -r '.tag_name | sub("^v"; "")')
-          CORERULESET_LVER=$(curl -fsSL "https://api.github.com/repos/coreruleset/coreruleset/releases/latest" | grep -oP '"tag_name": "\K[^"]+' | sed 's/v//')
-          NGX_TAG=$(docker run --rm nginx:alpine sh -c 'cat /etc/alpine-release | cut -d "." -f 1-2')
-          if [ -z "$NGX_LVER" ] || [ -z "$ZSTD_LVER" ] || [ -z "$CORERULESET_LVER" ] || [ -z "$NGX_TAG" ]; then
-            echo 'Error: Required parameters cannot be empty.' && exit 1
-          fi
-          echo "NGX_CVER=${NGX_CVER}" >> $GITHUB_ENV
-          echo "NGX_LVER=${NGX_LVER}" >> $GITHUB_ENV
-          echo "ZSTD_LVER=${ZSTD_LVER}" >> $GITHUB_ENV
-          echo "CORERULESET_LVER=${CORERULESET_LVER}" >> $GITHUB_ENV
-          echo "NGX_TAG=${NGX_TAG}" >> $GITHUB_ENV
-          if [[ "$(echo -e "${{ env.NGX_LVER }}\n${{ env.NGX_CVER }}" | sort -V | head -n1)" != "${{ env.NGX_LVER }}" ]] || [[ -z "$NGX_CVER" ]]; then
-            echo "IS_RENEW=1" >> $GITHUB_ENV
+          NGX_CVER=$(curl -fsSL "https://hub.docker.com/v2/repositories/${{ env.DOCKER_USERNAME }}/nginx/tags" 2>/dev/null | \
+            jq -r ".results // [] | .[].name" | grep -v '^alpine$' | sort -Vr | head -n1 | cut -d'-' -f1 || echo "") && \
+          NGX_LVER=$(curl -fsSL "https://api.github.com/repos/nginx/nginx/releases/latest" | \
+            jq -r '.tag_name | sub("release-"; "")') && \
+          ZSTD_LVER=$(curl -fsSL "https://api.github.com/repos/facebook/zstd/releases/latest" | \
+            jq -r '.tag_name | sub("^v"; "")') && \
+          CORERULESET_LVER=$(curl -fsSL "https://api.github.com/repos/coreruleset/coreruleset/releases/latest" | \
+            grep -oP '"tag_name": "\K[^"]+' | sed 's/v//') && \
+          NGX_TAG=$(docker run --rm nginx:alpine sh -c 'cat /etc/alpine-release | cut -d "." -f 1-2') && \
+          if [ -z "$NGX_LVER" ] || [ -z "$ZSTD_LVER" ] || [ -z "$CORERULESET_LVER" ] || [ -z "$NGX_TAG" ]; then \
+            echo 'Error: Required parameters cannot be empty.' && exit 1; \
+          fi && \
+          echo "NGX_CVER=${NGX_CVER}" >> $GITHUB_ENV && \
+          echo "NGX_LVER=${NGX_LVER}" >> $GITHUB_ENV && \
+          echo "ZSTD_LVER=${ZSTD_LVER}" >> $GITHUB_ENV && \
+          echo "CORERULESET_LVER=${CORERULESET_LVER}" >> $GITHUB_ENV && \
+          echo "NGX_TAG=${NGX_TAG}" >> $GITHUB_ENV && \
+          if [[ "$(echo -e "${{ env.NGX_LVER }}\n${{ env.NGX_CVER }}" | sort -V | head -n1)" != "${{ env.NGX_LVER }}" ]] || \
+            [[ -z "$NGX_CVER" ]]; then \
+            echo "IS_RENEW=1" >> $GITHUB_ENV; \
           fi
 
       - name: 'Set up Docker QEMU'
