fix: build nginx

diff --git a/.github/workflows/build_nginx.yml b/.github/workflows/build_nginx.yml
--- a/.github/workflows/build_nginx.yml
+++ b/.github/workflows/build_nginx.yml
@@ -1,4 +1,4 @@
-name: Build and publish Nginx
+name: build and publish nginx
 
 on:
   workflow_dispatch:
@@ -6,6 +6,7 @@ on:
 jobs:
   build:
     runs-on: ubuntu-22.04
+    name: "build nginx image"
 
     steps:
       - name: Check out repository
@@ -32,39 +33,37 @@ jobs:
 
       - name: Get current version
         run: |
-          CURRENT_NGINX_VERSION=$(docker run --rm honeok/nginx:alpine nginx -V 2>&1 | grep 'nginx version:' | awk -F'/' '{print $2}')
-          if [[ -z $CURRENT_NGINX_VERSION ]]; then
-              echo "ERROR: current nginx version retrieval failed!"
-              exit 1
+          CURRENT_VERSION=$(docker run --rm honeok/nginx:alpine nginx -V 2>&1 | grep 'nginx version:' | awk -F'/' '{print $2}')
+          if [[ -z $CURRENT_VERSION ]]; then
+              echo "ERROR: current nginx version retrieval failed!" && exit 1
           fi
-          echo "CURRENT_NGINX_VERSION=${CURRENT_NGINX_VERSION}" >> $GITHUB_ENV
-          LATEST_NGX_TAG=$(docker run --rm nginx:alpine sh -c 'cat /etc/alpine-release | cut -d "." -f 1-2')
-          if [[ -z $LATEST_NGX_TAG ]]; then
-              echo "ERROR: current nginx tag retrieval failed"
-              exit 1
+          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
+          ALPINE_TAG=$(docker run --rm nginx:alpine sh -c 'cat /etc/alpine-release | cut -d "." -f 1-2')
+          if [[ -z $ALPINE_TAG ]]; then
+              echo "ERROR: current nginx tag retrieval failed" && exit 1
           fi
-          echo "LATEST_NGX_TAG=${LATEST_NGX_TAG}" >> $GITHUB_ENV
+          echo "ALPINE_TAG=${ALPINE_TAG}" >> $GITHUB_ENV
 
       - name: Compare nginx version
         run: |
-          if [[ "$(echo -e "${{ env.LATEST_NGINX_VERSION }}\n${{ env.CURRENT_NGINX_VERSION }}" | sort -V | head -n1)" != "${{ env.LATEST_NGINX_VERSION }}" ]]; then
-            echo "BUILD_DOCKER_IMAGE=true" >> $GITHUB_ENV
+          if [[ "$(echo -e "${{ env.LATEST_VERSION }}\n${{ env.CURRENT_VERSION }}" | sort -V | head -n1)" != "${{ env.LATEST_VERSION }}" ]]; then
+            echo "BUILD_IMAGE=true" >> $GITHUB_ENV
           else
-            echo "BUILD_DOCKER_IMAGE=false" >> $GITHUB_ENV
+            echo "BUILD_IMAGE=false" >> $GITHUB_ENV
           fi
 
       - name: Build and Push Docker Image
-        if: env.BUILD_DOCKER_IMAGE == 'true'
+        if: env.BUILD_IMAGE == 'true'
         uses: docker/build-push-action@v6.11.0
         with:
           context: "{{defaultContext}}:nginx"
           file: Dockerfile
           push: false
           tags: |
-            "honeok/nginx:${{ env.LATEST_NGINX_VERSION }}-alpine${{ env.LATEST_NGX_TAG }}"
+            "honeok/nginx:${{ env.LATEST_VERSION }}-alpine${{ env.ALPINE_TAG }}"
             "honeok/nginx:alpine"
           platforms: linux/386,linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/riscv64,linux/s390x
           build-args: |
-            NGINX_VERSION=${{ env.LATEST_NGINX_VERSION }}
+            NGINX_VERSION=${{ env.LATEST_VERSION }}
             ZSTD_VERSION=${{ env.ZSTD_VERSION }}
             CORERULESET_VERSION=${{ env.CORERULESET_VERSION }}
