update

diff --git a/.github/workflows/h-ui.yml b/.github/workflows/h-ui.yml
--- a/.github/workflows/h-ui.yml
+++ b/.github/workflows/h-ui.yml
@@ -25,15 +25,11 @@ jobs:
           HUI_CVER="$(wget -qO- --tries=5 "https://hub.docker.com/v2/repositories/honeok/h-ui/tags" | grep -o '"name":"[^"]*"' | sed 's/"name":"//;s/"//' | grep -v '^latest$' | sort -Vr | head -n1 || echo "")"
           HUI_LTAG="$(wget -qO- --tries=5 "https://api.github.com/repos/jonssonyan/h-ui/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')"
           HUI_LVER="${HUI_LTAG#v}"
-          if [[ -z "$HUI_LTAG" || -z "$HUI_LVER" ]]; then
-            echo 'Error: Required parameters cannot be empty.' && exit 1
-          fi
+          [[ -z "$HUI_LTAG" || -z "$HUI_LVER" ]] && echo 'Error: Required parameters cannot be empty.' && exit 1
           echo "HUI_CVER=$HUI_CVER" >> $GITHUB_ENV
           echo "HUI_LTAG=$HUI_LTAG" >> $GITHUB_ENV
           echo "HUI_LVER=$HUI_LVER" >> $GITHUB_ENV
-          if [[ ( "$(echo -e "$HUI_LVER\n$HUI_CVER" | sort -V | head -n1)" != "$HUI_LVER" ) || -z "$HUI_CVER" ]]; then
-            echo "IS_RENEW=1" >> $GITHUB_ENV
-          fi
+          [[ ( "$(echo -e "$HUI_LVER\n$HUI_CVER" | sort -V | head -n1)" != "$HUI_LVER" ) || -z "$HUI_CVER" ]] && echo "IS_RENEW=1" >> $GITHUB_ENV
 
       - name: 'Set up Node.js'
         if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
@@ -44,11 +40,11 @@ jobs:
       - name: 'Download H-UI Source Code and Build frontend assets'
         if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
         run: |
-          cd /core/h-ui
+          cd /tmp
           apt-get update && apt-get install -y git
           git clone --depth=1 --branch "$HUI_LTAG" https://github.com/jonssonyan/h-ui.git
-          cd h-ui && rm -f Dockerfile
-          cd frontend && npm install && npm run build:prod
+          cd h-ui/frontend
+          npm install && npm run build:prod
           cd ../..
 
       - name: 'Set up Docker QEMU'
@@ -70,7 +66,7 @@ jobs:
         if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
         uses: docker/build-push-action@v6.17.0
         with:
-          context: "./core/h-ui"
+          context: "{{ defaultContext }}:core/h-ui"
           file: Dockerfile
           platforms: linux/386, linux/amd64, linux/arm/v6, linux/arm/v7, linux/arm64/v8, linux/ppc64le, linux/riscv64, linux/s390x
           tags: |
