update

diff --git a/.github/workflows/h-ui.yml b/.github/workflows/h-ui.yml
--- a/.github/workflows/h-ui.yml
+++ b/.github/workflows/h-ui.yml
@@ -25,11 +25,15 @@ jobs:
           HUI_CVER="$(wget -qO- --tries=5 "https://hub.docker.com/v2/repositories/honeok/h-ui/tags" | grep -o '"name":"[^"]*"' | sed 's/"name":"//;s/"//' | grep -v '^latest$' | sort -Vr | head -n1 || echo "")"
           HUI_LTAG="$(wget -qO- --tries=5 "https://api.github.com/repos/jonssonyan/h-ui/releases/latest" | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')"
           HUI_LVER="${HUI_LTAG#v}"
-          [[ -z "$HUI_CVER" || -z "$HUI_LTAG" || -z "$HUI_LVER" || ]] && echo 'Error: Required parameters cannot be empty.' && exit 1
+          if [[ -z "$HUI_CVER" || -z "$HUI_LTAG" || -z "$HUI_LVER" || ]]; then
+            echo 'Error: Required parameters cannot be empty.' && exit 1
+          fi
           echo "HUI_CVER=$HUI_CVER" >> $GITHUB_ENV
           echo "HUI_LTAG=$HUI_LTAG" >> $GITHUB_ENV
           echo "HUI_LVER=$HUI_LVER" >> $GITHUB_ENV
-          [[ ( "$(echo -e "$HUI_LVER\n$HUI_CVER" | sort -V | head -n1)" != "$HUI_LVER" ) || -z "$HUI_CVER" ]] && echo "IS_RENEW=1" >> $GITHUB_ENV
+          if [[ ( "$(echo -e "$HUI_LVER\n$HUI_CVER" | sort -V | head -n1)" != "$HUI_LVER" ) || -z "$HUI_CVER" ]]; then
+            echo "IS_RENEW=1" >> $GITHUB_ENV
+          fi
 
       - name: 'Set up Node.js'
         if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
