up

diff --git a/.github/workflows/ipinfo.yml b/.github/workflows/ipinfo.yml
--- a/.github/workflows/ipinfo.yml
+++ b/.github/workflows/ipinfo.yml
@@ -24,13 +24,15 @@ jobs:
       - name: 'Fetch Versions'
         run: |
           NGX_LVER="$(wget -qO- --tries=5 "https://api.github.com/repos/nginx/nginx/releases/latest" | grep -oP '"tag_name": "\K[^"]+' | sed 's/release-//')"
+          NGX_ALPINE_LVER="$(docker run --rm nginx:stable-alpine sh -c "nginx -v 2>&1 | awk -F'/' '{print \$NF}'")"
           GEOIP2_TAG="$(wget -qO- --tries 5 "https://api.github.com/repos/leev/ngx_http_geoip2_module/releases/latest" | grep -o '"tag_name": *"[^"]*"' | sed 's/.*"v\?\([^"]*\)".*/\1/')"
-          [[ -z "$NGX_LVER" || -z "$GEOIP2_TAG" ]] && { echo 'Error: Required parameters cannot be empty.'; exit 1; }
+          [[ -z "$NGX_LVER" || -z "$NGX_ALPINE_LVER" || -z "$GEOIP2_TAG" ]] && { echo 'Error: Required parameters cannot be empty.'; exit 1; }
           echo "NGX_LVER=$NGX_LVER" >> $GITHUB_ENV
           echo "GEOIP2_TAG=$GEOIP2_TAG" >> $GITHUB_ENV
+          [[ "$NGX_LVER" == "$NGX_ALPINE_LVER" ]] && echo "IS_RENEW=1" >> $GITHUB_ENV
 
       - name: 'Download GeoLite2 mmdb file'
-        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
+        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
         run: |
           cd ${{ github.workspace }}/forge/ipinfo
           wget --tries=5 -qO GeoLite2-ASN.mmdb "https://github.com/xjasonlyu/maxmind-geoip/releases/latest/download/ASN.mmdb"
@@ -43,22 +45,22 @@ jobs:
           sha256sum -c GeoLite2-Country.mmdb.sha256
 
       - name: 'Set up Docker QEMU'
-        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
+        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
         uses: docker/setup-qemu-action@v3.6.0
 
       - name: 'Set up Docker Buildx'
-        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
+        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
         uses: docker/setup-buildx-action@v3.10.0
 
       - name: 'Login to DockerHub'
-        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
+        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
         uses: docker/login-action@v3.4.0
         with:
           username: ${{ env.DOCKER_USERNAME }}
           password: ${{ env.DOCKER_PASSWORD }}
 
       - name: 'Build and Push ipinfo image'
-        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
+        if: env.IS_RENEW == 1 || github.event_name == 'workflow_dispatch'
         uses: docker/build-push-action@v6.18.0
         with:
           context: ${{ github.workspace }}/forge/ipinfo
