update

diff --git a/.github/workflows/x-ui.yml b/.github/workflows/x-ui.yml
--- a/.github/workflows/x-ui.yml
+++ b/.github/workflows/x-ui.yml
@@ -1,4 +1,4 @@
-name: 'Build x-ui image'
+name: 'Build and publish x-ui '
 
 on:
   workflow_dispatch:
@@ -7,7 +7,7 @@ on:
 
 jobs:
   build:
-    name: 'Build x-ui image'
+    name: 'Build and publish x-ui '
     runs-on: ubuntu-latest
     env:
       DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
@@ -19,20 +19,20 @@ jobs:
           fetch-depth: 0
           submodules: true
 
-    #   - name: 'Contrast Sing-box version'
-    #     run: |
-    #       LATEST_VERSION=$(curl -fsSL "https://api.github.com/repos/XTLS/Xray-core/releases" | jq -r 'map(select(.prerelease == true)) | sort_by(.created_at) | last | .tag_name' | sed 's/^v//')
-    #       CURRENT_VERSION=$(curl -Lsk "https://hub.docker.com/v2/repositories/honeok/sing-box/tags" | jq -r '.results // [] | .[].name' 2>/dev/null | grep -v '^latest$' | sort -Vr | head -n 1 || echo "")
-    #       if [ -z "$LATEST_VERSION" ]; then
-    #         echo "Error: Failed to obtain the latest version!" && exit 1
-    #       fi
-    #       echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_ENV
-    #       echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
-    #       if [[ "$(echo -e "${LATEST_VERSION}\n${CURRENT_VERSION}" | sort -V | head -n1)" != "$LATEST_VERSION" ]] || [[ -z "$CURRENT_VERSION" ]]; then
-    #         echo "BUILD_IMAGE=true" >> "$GITHUB_ENV"
-    #       else
-    #         echo "BUILD_IMAGE=false" >> $GITHUB_ENV
-    #       fi
+      - name: 'Contrast x-ui version'
+        run: |
+          LATEST_VERSION=$(curl -fsSL "https://api.github.com/repos/XTLS/Xray-core/releases" | jq -r 'map(select(.prerelease == true)) | sort_by(.created_at) | last | .tag_name' | sed 's/^v//')
+          CURRENT_VERSION=$(curl -fsSL "https://hub.docker.com/v2/repositories/pakho611/x-ui/tags" | jq -r '.results // [] | .[].name' 2>/dev/null | grep -v '^latest$' | sort -Vr | head -n 1 | awk -F - '{print $2}' || echo "")
+          if [ -z "$LATEST_VERSION" ]; then
+            echo "Error: Failed to obtain the latest version!" && exit 1
+          fi
+          echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_ENV
+          echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
+          if [[ "$(echo -e "${LATEST_VERSION}\n${CURRENT_VERSION}" | sort -V | head -n1)" != "$LATEST_VERSION" ]] || [[ -z "$CURRENT_VERSION" ]]; then
+            echo "BUILD_IMAGE=true" >> "$GITHUB_ENV"
+          else
+            echo "BUILD_IMAGE=false" >> $GITHUB_ENV
+          fi
 
       - name: 'Set up Docker QEMU'
         if: env.BUILD_IMAGE == true || github.event_name == 'workflow_dispatch'
@@ -57,6 +57,6 @@ jobs:
           file: Dockerfile
           push: true
           tags: |
-            "${{ env.DOCKER_USERNAME }}/x-ui:xray-25.3.31"
+            "${{ env.DOCKER_USERNAME }}/x-ui:xray-${{ env.LATEST_VERSION }}"
             "${{ env.DOCKER_USERNAME }}/x-ui:latest"
           platforms: linux/amd64, linux/arm/v6, linux/arm64/v8
