update

diff --git a/.github/workflows/x-ui.yml b/.github/workflows/x-ui.yml
--- a/.github/workflows/x-ui.yml
+++ b/.github/workflows/x-ui.yml
@@ -21,17 +21,28 @@ jobs:
 
       - name: 'Contrast x-ui version'
         run: |
-          LATEST_VERSION=$(curl -fsSL "https://api.github.com/repos/XTLS/Xray-core/releases" | jq -r 'map(select(.prerelease == true)) | sort_by(.created_at) | last | .tag_name' | sed 's/^v//')
-          CURRENT_VERSION=$(curl -fsSL "https://hub.docker.com/v2/repositories/pakho611/x-ui/tags" | jq -r '.results // [] | .[].name' 2>/dev/null | grep -v '^latest$' | sort -Vr | head -n 1 | awk -F - '{print $2}' || echo "")
-          if [ -z "$LATEST_VERSION" ]; then
-            echo "Error: Failed to obtain the latest version!" && exit 1
-          fi
+          LATEST_VERSION=$(curl -fsSL "https://api.github.com/repos/XTLS/Xray-core/releases" | \
+            jq -r 'map(select(.prerelease == true)) | sort_by(.created_at) | last | .tag_name' | \
+            sed 's/^v//') && \
+          CURRENT_VERSION=$(bash -c 'set -o pipefail; curl -fsSL "https://hub.docker.com/v2/repositories/honeok/x-ui/tags" 2>/dev/null | \
+            jq -r ".results // [] | .[].name" | \
+            grep -v "^latest$" | \
+            sort -Vr | \
+            head -n 1 | \
+            awk -F - "{print \$2}" || echo ""') && \
+          if [ -z "$LATEST_VERSION" ]; then \
+            echo "Error: Failed to obtain the latest version!" && exit 1; \
+          fi && \
           echo "LATEST_VERSION=${LATEST_VERSION}" >> $GITHUB_ENV
           echo "CURRENT_VERSION=${CURRENT_VERSION}" >> $GITHUB_ENV
-          if [[ "$(echo -e "${LATEST_VERSION}\n${CURRENT_VERSION}" | sort -V | head -n1)" != "$LATEST_VERSION" ]] || [[ -z "$CURRENT_VERSION" ]]; then
-            echo "BUILD_IMAGE=true" >> "$GITHUB_ENV"
-          else
-            echo "BUILD_IMAGE=false" >> $GITHUB_ENV
+
+          echo "$LATEST_VERSION $CURRENT_VERSION"
+
+          if [[ "$(echo -e "${LATEST_VERSION}\n${CURRENT_VERSION}" | sort -V | head -n1)" != "$LATEST_VERSION" ]] || \
+            [[ -z "$CURRENT_VERSION" ]]; then \
+            echo "BUILD_IMAGE=true" >> "$GITHUB_ENV"; \
+          else \
+            echo "BUILD_IMAGE=false" >> "$GITHUB_ENV"; \
           fi
 
       - name: 'Set up Docker QEMU'
