fix
Signed-off-by: havario <157877551+havario@users.noreply.github.com>

diff --git a/.github/workflows/xray.yaml b/.github/workflows/xray.yaml
--- a/.github/workflows/xray.yaml
+++ b/.github/workflows/xray.yaml
@@ -16,8 +16,52 @@ concurrency:
   group: "${{ github.workflow }}-${{ github.ref }}"
   cancel-in-progress: true
 
+env:
+  DOCKERHUB_REPO: ${{ secrets.DOCKER_USERNAME }}/xray
+
 jobs:
+  check:
+    name: "Pre check"
+    runs-on: ubuntu-latest
+    outputs:
+      trigger: ${{ steps.bump_version.outputs.trigger }}
+      xray_tag: ${{ steps.bump_version.outputs.xray_tag }}
+      xray_version: ${{ steps.bump_version.outputs.xray_version }}
+
+    steps:
+      - name: "Checkout repository"
+        uses: actions/checkout@v6
+        with:
+          fetch-depth: 0
+
+      - name: "Fetch Versions and Decide"
+        id: bump_version
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          set -eEuxo pipefail
+          TRIGGER="false"
+          LATEST_TAG="$(wget -qO- --tries=5 --header="Authorization: token $GITHUB_TOKEN" \
+            https://api.github.com/repos/XTLS/Xray-core/releases | sed -n 's/.*"tag_name": *"\(v[^"]*\)".*/\1/p' | sort -rV | head -n1)"
+          LATEST_VER=${LATEST_TAG#v}
+          CURRENT_VER="$(wget -qO- --tries=5 https://hub.docker.com/v2/repositories/$DOCKERHUB_REPO/tags 2>/dev/null | \
+            grep -o '"name":"[^"]*"' | awk -F'"' '$4!="latest"{print $4}' | sort -rV | head -n1 || true)"
+
+          echo "xray_tag=${LATEST_TAG}" >> "$GITHUB_OUTPUT"
+          echo "xray_version=${LATEST_VER}" >> "$GITHUB_OUTPUT"
+          if [[ "$(printf '%s\n%s\n' "$LATEST_VER" "$CURRENT_VER" | sort -V | head -n1)" != "$LATEST_VER" ]] || \
+            [[ -z "$CURRENT_VER" && -n "$LATEST_VER" ]] || [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
+            echo "Build required."
+            TRIGGER="true"
+          else
+            echo "No build required."
+          fi
+          echo "trigger=${TRIGGER}" >> "$GITHUB_OUTPUT"
+
   release:
+    needs:
+      - check
+    if: needs.check.outputs.trigger == 'true'
     strategy:
       fail-fast: true
       matrix:
@@ -42,7 +86,7 @@ jobs:
         run: |
           set -eEuxo pipefail
           mkdir src
-          git clone --depth=1 --branch v25.12.8 https://github.com/XTLS/Xray-core.git src
+          git clone --depth=1 --branch ${{ needs.check.outputs.xray_tag }} https://github.com/XTLS/Xray-core.git src
 
       - name: "Setup Go"
         uses: actions/setup-go@v6
@@ -84,3 +128,145 @@ jobs:
           path: core/xray/src/${{ env.BINARY_NAME }}
           if-no-files-found: error
           retention-days: 1
+
+  build:
+    needs:
+      - check
+      - release
+    strategy:
+      fail-fast: true
+      matrix:
+        platform:
+          - linux/386
+          - linux/amd64
+          - linux/arm/v6
+          - linux/arm/v7
+          - linux/arm64
+          - linux/ppc64le
+          - linux/riscv64
+          - linux/s390x
+    runs-on: ubuntu-latest
+    name: "Build image"
+
+    steps:
+      - name: "Prepare"
+        run: |
+          PLATFORM=${{ matrix.platform }}
+          echo "PLATFORM_PAIR=${PLATFORM//\//-}" >> "$GITHUB_ENV"
+
+      - name: "Checkout repository"
+        uses: actions/checkout@v6
+        with:
+          fetch-depth: 0
+
+      - name: "Download binary"
+        uses: actions/download-artifact@v7
+        with:
+          name: binary-${{ env.PLATFORM_PAIR }}
+          path: .
+
+      # Find and make the binary executable
+      - name: "Prepare binary"
+        run: |
+          chmod +x xray-*
+          ls -la xray-*
+
+      - name: "Setup Docker QEMU"
+        uses: docker/setup-qemu-action@v3
+
+      - name: "Setup Docker Buildx"
+        uses: docker/setup-buildx-action@v3
+
+      - name: "Login to DockerHub"
+        uses: docker/login-action@v3
+        with:
+          registry: docker.io
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+      - name: "Extract Docker metadata"
+        id: meta
+        uses: docker/metadata-action@v5
+        with:
+          images: ${{ env.DOCKERHUB_REPO }}
+          tags: |
+            type=raw,value=${{ needs.check.outputs.xray_version }}
+            type=raw,value=latest
+          labels: |
+            org.opencontainers.image.description=Xray, Penetrates Everything. Also the best v2ray-core. Where the magic happens. An open platform for various uses.
+            org.opencontainers.image.source=https://github.com/XTLS/Xray-core
+            org.opencontainers.image.title=Xray
+            org.opencontainers.image.url=https://xtls.github.io
+
+      - name: "Build and export"
+        id: build
+        uses: docker/build-push-action@v6
+        with:
+          context: core/xray/
+          platforms: ${{ matrix.platform }}
+          labels: ${{ steps.meta.outputs.labels }}
+          outputs: type=image,name=${{ env.DOCKERHUB_REPO }},push-by-digest=true,name-canonical=true,push=true
+
+      - name: "Export digest"
+        run: |
+          rm -rf /tmp/digests
+          mkdir -p /tmp/digests
+          digest="${{ steps.build.outputs.digest }}"
+          touch "/tmp/digests/${digest#sha256:}"
+
+      - name: "Upload artifact"
+        uses: actions/upload-artifact@v4
+        with:
+          name: digest-${{ env.PLATFORM_PAIR }}
+          path: /tmp/digests/*
+          if-no-files-found: error
+          retention-days: 1
+
+  merge:
+    needs:
+      - build
+    runs-on: ubuntu-latest
+    name: "Merge manifest"
+
+    steps:
+      - name: "Download digests"
+        uses: actions/download-artifact@v5
+        with:
+          path: /tmp/digests
+          pattern: digest-*
+          merge-multiple: true
+
+      - name: "Setup Docker Buildx"
+        uses: docker/setup-buildx-action@v3
+
+      - name: "Login to DockerHub"
+        uses: docker/login-action@v3
+        with:
+          registry: docker.io
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+
+      - name: "Extract Docker metadata"
+        id: meta
+        uses: docker/metadata-action@v5
+        with:
+          images: ${{ env.DOCKERHUB_REPO }}
+          tags: |
+            type=raw,value=${{ needs.check.outputs.xray_version }}
+            type=raw,value=latest
+          labels: |
+            org.opencontainers.image.description=Xray, Penetrates Everything. Also the best v2ray-core. Where the magic happens. An open platform for various uses.
+            org.opencontainers.image.source=https://github.com/XTLS/Xray-core
+            org.opencontainers.image.title=Xray
+            org.opencontainers.image.url=https://xtls.github.io
+
+      - name: "Create manifest list and push"
+        working-directory: /tmp/digests
+        run: |
+          docker buildx imagetools create \
+            $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< "$DOCKER_METADATA_OUTPUT_JSON") \
+            $(printf '${{ env.DOCKERHUB_REPO }}@sha256:%s ' *)
+
+      - name: "Inspect image"
+        run: |
+          docker buildx imagetools inspect ${{ env.DOCKERHUB_REPO }}:${{ needs.check.outputs.xray_version }}
